### PR TITLE
Latest Tween.js ES6

### PR DESCRIPTION
**Pull request by dalisoft**
## Features

- [x] Compiled Single-file for performance and simple, clean result
- [x] Works all method
- [x] Works on Browser too ( Chrome 55+ )
- [x] You like `import` and you don't want `single` file? You can split files and make it modular (requires some time)

## Usage
* this javascript usage same as default Tween.js

```javascript
var tween = new TWEEN.Tween({x:0}).to({x:100}).easing(TWEEN.Easing.Quadratic.InOut).onUpdate((object, elapsed) => {
	console.log(object);
}).start();

requestAnimationFrame(function anim(time){
	requestAnimationFrame(anim);
	TWEEN.update(time);
});
```

## If this makes `V2` starting...
* Similar to `TweenManager`, but `Group Manager` is <a href="https://github.com/tweenjs/tween.js/pull/311">here</a>
* Classes are made, so everyone can extend the class with 
```javacript
class MyExtend extends TWEEN.Tween { // class MyExtend extends TWEEN {
static Foo () {}
Bar (x) {
return x * 5;
}
```

## NOTE
* If you need this work on back to IE9 (even IE8 possible), you need `BabelJS`.
* You can try <a href="https://babeljs.io/repl">Babel REPL</a>
* Or you can try Babel in `NodeJS (npm)` via `babel-loader` plug-in
* It's starting, when we improve it together it will be better like `emit` instead of `onUpdate, onStart` or even new things.
* Compiling `build` and `dev` version takes just `~2min` in `Webpack+Babel+NodeJS`

### CODE REVIEW

**Comment by sole** [comment]
Cool stuff! Thanks. I merged it.

Since you know what you're doing, would you like to lead this repo? It would make a lot of sense!

**Comment by dalisoft** [comment]
Hi. Thanks. 
Wow. Wow. This is first my pr that merged. I am impressed

**Comment by dalisoft** [comment]
This is very good words. If you like. I am very happy to lead it

**Comment by dalisoft** [comment]
There maybe joins @mikebolt and other contributors for better improving. Would you like emit events for callbacks or just callback as function/method (current variant). I am do everything as possible to make it better

**Comment by sole** [comment]
The truth is that I do not *need* an ES6 version, and so I do not know what features are required or not! I think it's best if people who need/want it are the ones working on it (like you!).

**Comment by dalisoft** [comment]
Thanks. I can add addinational features like play, pause?

**Comment by sole** [comment]
Sure why not? As long as people know this is an experimental version, you should be free to experiment with new features. You do not need my permission - I am going to make you owner of the repo.

**Comment by dalisoft** [comment]
Thanks a lot. I make this best as possible

**Pull request merged**
