### PR TITLE
Additionaly check in TWEEN.Tween.to function

### PR DESCRIPTION
**Pull request by seIncorp**
I added additionally check in TWEEN.Tween.to, if the this.object is equal to this._valuesEnd. If not all excess parameters are removed.

### CODE REVIEW

**Comment by dalisoft** [comment]
Thanks. But this feature causes some bugs/collision in tweening. I don’t think this needed

**Comment by seIncorp** [comment]
> Thanks. But this feature causes some bugs/collision in tweening. I don’t think this needed

There was some issues with white spaces.

**Comment by dalisoft** [comment]
I see, CI passed, but i have real experience with these bugs. The bug will appear when two tweens with same node, like independent tweening

**Comment by seIncorp** [comment]
> I see, CI passed, but i have real experience with these bugs. The bug will appear when two tweens with same node, like independent tweening

Now I see what you meant. If you want you can remove it or try to fix this issue.

**Comment by dalisoft** [comment]
These issue may appear after merging this PR, now this issue i fixed with Store cache

**Pull request closed without merging**
