### PR TITLE
Initial attempt at ES6ifing

### PR DESCRIPTION
**Pull request by salzhrani**
Here is an unsolicited attempt to make an ES2015-tween. Hope you think it is useful, and would understand if it gets rejected. Included is a naive attempt at benchmarking the reformat, if it is any good it shows no negative impact of the reformating.

### CODE REVIEW

**Comment by salzhrani** [comment]
feedback @sole ?

**Comment by sole** [comment]
@salzhrani Sorry no feedback yet - I have been really busy with something else.
Thanks for the attempt!

Feedback then! :-)

* My idea was to separate stuff into other modules and have the top module require those (but I don't really know how I'd do that). So far the main `tween.js` file is huge and unwieldy and there's no way of knowing what's going on
* The way tweens (the objects) work also is perhaps not the clearest; instead of carrying the confusing stuff over, it would maybe be interesting to see if we can use this (re)write to make it better instead of a literal port
* I'm not too happy about having to check in a `dist/` compiled version as they always get out of date
* I'm also not sure about what do we test, do we test the source or the compiled? With which runtime? etc

And then for the obvious:

* I would not use bower, let's really shed 'old stuff' for this new version
* The README shows things that are outdated

**Comment by salzhrani** [comment]
I have updated the PR ... mainly splitting the library into separate modules, update the build and test scripts, use ESlint instead of JSHint.

For me the main issues with the current API are:
+ User is responsible for advancing the tween, `Tween.update` unless there is a use case for that the user should not worry about animation frames and updating the tween
+ Managing tween array, I do not see the benefit of adding and removing tweens from the update array. the user should be concerned with starting, stopping and pausing a tween.

besides that the API seems suffice.

**Comment by dalisoft** [comment]
@sole @salzhrani Look at <a href="https://github.com/tweenjs/es6-tween/pull/7">My PR</a>.
On `npm` using `babel` and `webpack` compiling minifed and source version takes less than 2-minutes.
It's time to move to ES6 version.
NOTE: It's starting, when we improve it together it will be better like `emit` instead of `onUpdate, onStart` or even new things.

**Pull request closed without merging**
